calculadora/urls.py

from django.urls import path
from . import views

app_name = 'calculadora'

urlpatterns = [
    path('Home_Calculadora/',views.v_iniciocal, name='inicio'),
  

]



inicial/urls.py

from django.urls import path
from . import views

app_name = 'inicio'

urlpatterns = [
    path('',views.v_host, name ='index'),

    

 



  

]



orcamento/urls.py

from django.urls import path
from . import views

app_name = 'orcamento'

urlpatterns = [
    
    path('Home_Orcamento/',views.v_inicioor, name='index'),
    path('Consulta/',views.v_cons, name='consulta'),

  

]



sites_proj/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/',admin.site.urls, ),
    path('', include('inicial.urls')),
    path('calculadora/', include('calculadora.urls')),
    path('Uber/', include('uber.urls')),
    path('Orcamento/', include('orcamento.urls')),


    
]



uber/urls.py
from django.urls import path
from . import views

app_name = 'uber'

urlpatterns = [
    path('Home_Uber/',views.v_iniciouber,name='home'),
    path('Contato/',views.v_contato,name='contato'),
    path('Login/',views.v_login,name='login'),
    path('Mobile/',views.v_mobile,name='mobile'),
    path('Register_Motorista/',views.v_registerMoto,name='registerMoto'),
    path('Register/',views.v_register,name='register'),
    path('Servicos/',views.v_servicos,name='servicos'),
    path('Sobre/',views.v_sobre,name='sobre'),
    path('Uber_Eats/',views.v_eats,name='eats'),
    
    

 



  

]

calculadora/models.py
from django.db import models

# Create your models here.

inicial/models.py
from django.db import models

# Create your models here.

orcamento/models.py
from django.db import models

# Create your models here.

uber/models.py
from django.db import models

# Create your models here.

calculadora/views.py
from django.shortcuts import render
from django.http import HttpResponse

def v_iniciocal(request):

    return render(request, 'calculadora/paginas/inicio.html')




inicial/views.py
from django.shortcuts import render
from django.http import HttpResponse


def v_host(request):

    return render(request,'inicial/paginas/home.html')

orcamento/views.py
from django.shortcuts import render
from django.http import HttpResponse

def v_inicioor(request):

    return render(request,'orcamento/paginas/index.html')


def v_cons(request):

    return render(request,'orcamento/paginas/consulta.html')


uber/views.py
from django.shortcuts import render
from django.http import HttpResponse


def v_iniciouber(request):

    return render(request, 'Uber/paginas/index.html')

def v_mobile(request):

    return render(request, 'Uber/paginas/mobile.html')

def v_contato(request):

    return render(request, 'Uber/paginas/contato.html')

def v_login(request):

    return render(request, 'Uber/paginas/login.html')

def v_registerMoto(request):

    return render(request, 'Uber/paginas/register_motorista.html')

def v_register(request):

    return render(request, 'Uber/paginas/register.html')

def v_servicos(request):

    return render(request, 'Uber/paginas/servicos.html')

def v_sobre(request):

    return render(request, 'Uber/paginas/sobre.html')

def v_eats(request):

    return render(request, 'Uber/paginas/uber_eats.html')

calculadora/templates/calculadora/parciais/head.html
{% load static %}

<html>
	<head>
		<title>Calculadora</title>
		<link rel="stylesheet" href="{%static 'calculadora/css/style.css'%}"></script>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
	</head>

inicial/templates/inicial/paginas/home.html
<!DOCTYPE html>
<html>
    
{%include 'inicial/parciais/head.html'%}

</head>
<body>
  <a href="{%url 'calculadora:inicio'%}" class="button">Calculadora</a>
  <a href="{%url 'uber:home'%}" class="button">Uber</a>
  <a href="{%url 'orcamento:index'%}" class="button">Orçamento</a>
</body>
</html>

inicial/templates/inicial/parciais/head.html
{% load static %}


<head>
  <title>Home Sites Django</title>
  <link rel="icon" href="https://brandslogos.com/wp-content/uploads/images/django-logo.png">
		<link rel="stylesheet" href="{%static 'inicial/css/style.css'%}"></script>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
</head>

orcamento/templates/orcamento/paginas/consulta.html
{%load static%}
<html>
	{%include 'orcamento/parciais/head.html'%}


  <body onload="listarTodasDespesas()">

   
    {%include 'orcamento/parciais/nav.html'%}
    
    <li class="nav-item ">
    <a class="nav-link" href="{%url 'orcamento:index'%}">Cadastro</a>
  </li>
  <li class="nav-item active">
    <a class="nav-link" href="{%url 'orcamento:consulta'%}">Consulta</a>
  </li>
</ul>

</div>
</div>
</nav>

    <div class="container">
      <div class="row mb-5">
        <div class="col">
          <h1 class="display-4">Consulta de despesas</h1>
        </div>
      </div>

      {%include 'orcamento/parciais/form.html'%}

      
      
        <div class="col-md-2 d-flex justify-content-end">
          <button onclick="pesquisarDespesa()" type="button" class="btn btn-primary">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>

      <div class="row">
        <div class="col">
          <table class="table" >
            <thead>
              <tr>
                <th>Data</th>
                <th>Tipo</th>
                <th>Descrição</th>
                <th>Valor</th>
                <th></th>
              </tr>
            </thead>

            <tbody id="tabelaDespesas"></tbody>

          </table>
        </div>
      </div>
    </div>

    <!-- Modal -->
    
    {%include 'orcamento/parciais/modal.html'%}

  </body>	

</html>

orcamento/templates/orcamento/paginas/index.html
{% load static %}
{%include 'orcamento/parciais/head.html'%}




<html>
	

  <body>

    {%include 'orcamento/parciais/nav.html'%}
    
    <li class="nav-item active">
    <a class="nav-link" href="{%url 'orcamento:index'%}">Cadastro</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{%url 'orcamento:consulta'%}">Consulta</a>
  </li>
</ul>

</div>
</div>
</nav>

    <div class="container">
      <div class="row">
        <div class="col mb-5">
          <h1 class="display-4">Registro de nova despesa</h1>
        </div>
      </div>

      


      {%include 'orcamento/parciais/form.html'%}

      

        <div class="col-md-2 d-flex justify-content-end">
          <button type="button" class="btn btn-primary" onclick="cadastrarDespesa()">
            <i class="fas fa-plus"></i>
          </button>
        </div>
      </div>
    </div>

    <!-- Modal -->
    {%include 'orcamento/parciais/modal.html'%}


  </body>	

</html>



orcamento/templates/orcamento/parciais/nav.html
{%load static%}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-5">
    <div class="container">
      <a class="navbar-brand" href="{%url 'orcamento:index'%}">
         <img src="{%static 'orcamento/img/logo.png'%}" width="50" height="35" alt="Orçamento pessoal">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">


           

uber/templates/uber/paginas/index.html
{%load static%}

  {%include 'uber/parciais/head.html'%}
    
    <body>
    
        <div class="estrutura">
            
        <!-- header --> 
            {%include 'uber/parciais/header.html'%}

        <!-- menu lateral --> 
            {%include 'uber/parciais/menu_lateral.html'%}


            
            <!-- Conteúdo Principal -->
            <main class="content">
                
                <!-- Ínicio -->
                <div class="bem_vindo">
                    <div>
                        <div>
                            <h2>Uber Brasil</h2>
                            <p>Seja bem-vindo ao site da maior empresa de transporte privado no mercado!</p>
                        </div>

                        {%include 'uber/parciais/icons_head.html'%}

           
                <!-- Fim Ínicio -->
                
                <!-- Conheça-nos -->
                <div class="conheca_nos">
                    <img src="{%static 'uber/img/uber_quem_somos.jpg'%}" alt="Quem somos">
                    <div>
                        <h3>Conheça-nos</h3>
                        <p>Conheça um pouco sobre a nossa empresa, a história da Uber e seus parceiros mais próximos.</p>
                        <a href="{%url 'uber:sobre'%}">Saiba mais<i class="fas fa-angle-right"></i></a>
                    </div>
                </div>
                <!-- Fim Conheça-nos-->
                
                <!-- Como funciona -->
                <div class="como_funciona bg_azul">
                    <img src="{%static 'uber/img/uber_funcionamento.jpg'%}">
                    <div>
                        <h3>Como funciona</h3>
                        <p>Saiba como utilizar os serviços que a Uber proporciona de forma rápida e prática, esclareça todas as suas dúvidas sobre o aplicativo e plataforma Uber.</p>
                        <a href="{%url 'uber:sobre'%}">Saiba mais<i class="fas fa-angle-right"></i></a>
                    </div>
                </div>
                <!-- Fim Como Funciona -->
                
                <!-- Serviços -->
                <div class="servicos">
                    <div class="mesclar">
                        <h3>Serviços para você</h3>
                        <p>Conheço abaixo os tipos de serviços que a Uber oferece para seus usuários!</p>
                        <a href="{%url 'uber:servicos'%}">Saiba mais<i class="fas fa-angle-right"></i></a>
                    </div>


                    {%include 'uber/parciais/ser_cat.html'%}
                    </div>
                    {%include 'uber/parciais/ser_eats.html'%}
                    </div>
                    {%include 'uber/parciais/ser_mob.html'%}
                    </div>


                </div>
                <!-- Fim Serviços -->
                
                <!-- Citação -->
                <blockquote class="citacao bg_verde">
                    <p>"Comentário de alguém super importante sobre a Uber..."</p>
                    <cite>Tal Pessoa, idade, o que faz</cite>
                </blockquote>
                <!-- Fim Citação -->
                
                <div class="botoes">
                    <a href="{%url 'uber:register'%}" class="botao_cadastro">
                        <span>Cadastre-se como Passageiro</span>
                        <i class="fas fa-arrow-right"></i>
                    </a>
                    <a href="{%url 'uber:registerMoto'%}" class="botao_cadastro">
                        <span>Cadastre-se como Motorista</span>
                        <i class="fas fa-arrow-right"></i>
                    </a>
                </div>
                
            </main>
            <!-- Fim Conteúdo Principal -->
            
                 
            {%include 'uber/parciais/footer.html'%}
        </div>
    
    </body>
</html>

uber/templates/uber/paginas/servicos.html
{%load static%}

  {%include 'uber/parciais/head.html'%}
    
    <body>
    
        <div class="estrutura">
            
            <!-- header --> 
            {%include 'uber/parciais/header.html'%}

        <!-- menu lateral --> 
            {%include 'uber/parciais/menu_lateral.html'%}
            <!-- Fim Cabeçalho -->
            
            <!-- Conteúdo Principal -->
            <main class="content">
                
                <!-- Ínicio -->
                <div class="bem_vindo">
                    <div>
                        <div>
                            <h2>Serviços</h2>
                            <p>Conheço abaixo os tipos de serviços que a Uber oferece para seus usuários!</p>
                        </div>
                        {%include 'uber/parciais/icons_head.html'%}

                <!-- Fim Ínicio -->
                
                <!-- Categorias -->
                <div class="servicos_categorias bg_cinza">
                    <div class="mesclar">
                        <h3>Categorias</h3>
                        <p>Um uber para cada necessidade, descubra qual o tipo de Uber que melhor se encaixa a suas necessidades e ao seu bolso.</p>
                    </div>
    
                    <div class="mesclar">
                        <h4>Uber X</h4>
                        <h5>Ideal para sua locomoção cotidiana</h5>
                    </div>
                    <img src="{%static 'uber/img/uber_x_cartao.png'%}" alt="Categorias">
                    <div class="uber_x">
                        <p>A principal e mais usada opção da Uber, o UberX oferece viagens com preços acessíveis em carros compactos de quatro portas e ar-condicionado. Presente em todas as cidades brasileiras onde a Uber opera, é o tipo de veículo ideal para você que precisa se deslocar pela cidade durante os compromissos do dia a dia com rapidez e praticidade.</p>
                    </div>
                    
                    <div class="mesclar">
                        <h4>Uber Black</h4>
                        <h5>Viagens exclusivas em veículos de alto nível</h5>
                    </div>
                    <img src="{%static 'uber/img/uber_black_cartao.png'%}" alt="Uber Eats">
                    <div class="uber_black">
                        <p>Primeira a ser criada entre as categorias da Uber, o Uber Black possui carros tipo sedan, tais como Toyota Corolla, Ford Fusion, Volkswagen Jetta e outros. Todos os veículos desta categoria possuem bancos de couro, oferecendo um conforto maior para você que busca uma viagem exclusiva para uma reunião de negócios, um compromisso importante ou um jantar especial. Todos os carros utilizados no Uber Black são da cor preta, e a opção está atualmente disponível em seis cidades brasileiras: Curitiba, São Paulo, Rio de Janeiro, Belo Horizonte, Brasília e Porto Alegre.</p>
                    </div>
                    
                    <div class="mesclar">
                        <h4>Uber Comfort</h4>
                        <h5>Melhores carros e experiência premium</h5>
                    </div>
                    <img src="{%static 'uber/img/uber_comfort_cartao.jpg'%}">
                    <div class="uber_comfort">
                        <p>Desenvolvido para possibilitar uma experiência ainda mais confortável para os usuários, o Uber Comfort conecta você com  motoristas com veículos selecionados, bem avaliados e a possibilidade de seleção de preferências de conversa e temperatura antes do início da viagem.</p>
                    </div>
                    
                    <div class="mesclar">
                        <h4>Uber Juntos</h4>
                        <h5>Compartilhando viagens e economizando</h5>
                    </div>
                    <img src="{%static 'uber/img/uber_juntos_cartao.jpg'%}">
                    <div class="uber_juntos">
                        <p>Criado como uma alternativa para unir usuários que estejam viajando para uma direção similar, o Uber Juntos (antigo Uber Pool) está atualmente disponível em somente algumas cidades no Brasil. Com ele, você pode ter um custo de viagem mais acessível e ajudar a contribuir com o trânsito e com o meio ambiente, ajudando a diminuir o número de veículos nas ruas. Inovação entre as categorias da Uber, o Uber Juntos é indicado para você que está viajando sozinho ou com no máximo mais uma pessoa, conectando você a outros usuários da plataforma, a um excelente custo-benefício para todos.</p>
                    </div>
                    
                    <div class="mesclar">
                        <h4>Uber Bag</h4>
                        <h5>Mais espaço para suas malas ou pertences</h5>
                    </div>
                    <img src="{%static 'uber/img/uber_bag_cartao.png'%}">
                    <div class="uber_bag">
                        <p>Se você está indo ou voltando de uma longa viagem com algumas malas a mais, ou se precisa de mais espaço no porta malas, o Uber BAG é a modalidade que você procura. Os veículos desta categoria possuem porta-malas maior, podendo transportar suas bagagens com tranquilidade até seu destino final. A categoria Uber Bag está disponível apenas nas cidades de São Paulo e Brasília.</p>
                    </div>
                </div>
                <!-- Fim Categorias -->
                
                <!-- Serviços -->
                <div class="servicos servicos_inferior">

                    {%include 'uber/parciais/ser_eats.html'%}
                    <a href="{%url 'uber:eats'%}">Saiba mais<i class="fas fa-angle-right"></i></a>
                </div>
                    {%include 'uber/parciais/ser_mob.html'%}
                    <a href="{%url 'uber:mobile'%}">Saiba mais<i class="fas fa-angle-right"></i></a>
                  </div>
                </div>
                <!-- Fim Serviços -->
                
            </main>
            <!-- Fim Conteúdo Principal -->
            
            {%include 'uber/parciais/footer.html'%}

        </div>
    
    </body>
</html>

uber/templates/uber/paginas/uber_eats.html
{%load static%}

  {%include 'uber/parciais/head.html'%}
    
    
    <body>
    
        <div class="estrutura">
            
         <!-- header --> 
         {%include 'uber/parciais/header.html'%}

         <!-- menu lateral --> 
        {%include 'uber/parciais/menu_lateral.html'%}
            <!-- Conteúdo Principal -->
            <main class="content">
                
                <!-- Ínicio -->
                <div class="bem_vindo">
                    <div>
                        <div>
                            <h2>Serviços</h2>
                            <p>Conheço abaixo os tipos de serviços que a Uber oferece para seus usuários!</p>
                        </div>
                        {%include 'uber/parciais/icons_head.html'%}

                    
                 
                <!-- Fim Ínicio -->
                
                <!-- Inicio Uber Eats -->
                <div class="servicos_categorias categorias_uber_eats bg_verde">
                    <div class="mesclar">
                        <h3>Uber <span>Eats</span></h3>
                        <p>Utilizando o Uber Eats, com apenas um toque, receba em sua casa seu pedido de seu restaurante favorito.</p>
                    </div>
    
                    <div class="mesclar">
                        <h4>Delivery</h4>
                        <h5>Seu prato favorito com entrega da Uber</h5>
                    </div>
                    <img src="{%static 'uber/img/uber_eats_entregador.jpg'%}">
                    <div class="uber_x">
                        <p>O Uber Eats é o serviço de entrega de comidas da Uber, com atividade em 13 países e mais de 50 cidades. O app grátis está disponível para celulares Android e iPhone (iOS) e oferece cupons de desconto, suporte a diversos restaurantes e opções de cancelamento do pedido com reembolso. Além disso, ele experimenta o uso de drones nas entregas, com possibilidade chegada no Brasil em cinco anos. O serviço chegou ao Brasil em dezembro de 2016 com a promessa de rivalizar com os concorrentes iFood e SpoonRocket.</p>
                    </div>
                    
                    <div>
                        <h4>Como funciona?</h4>
                        <p>O usuário precisa baixar o aplicativo no smartphone, aguardar que ele encontre a localização ou acessar o site do Uber Eats (eats.uber.com) e inserir o endereço manualmente. Então, basta selecionar um dos restaurantes e lanchonetes disponíveis para a entrega, escolher o item desejado no cardápio e confirmar o pagamento. Caso prefira receber o pedido mais tarde, também é possível agendar um horário. Desse modo, é necessário esperar a chegada do entregador ao local dentro do período de tempo estimado.</p>
                    </div>
                    
                    <div>
                        <h4>Preços</h4>
                        <p>Diferente do concorrente iFood, que adiciona um percentual sobre o valor total para cobrar a entrega, o Uber Eats mantém uma taxa fixa de R$ 7,90 em cidades como São Paulo e Rio de Janeiro. No entanto, conforme o horário e a região onde a solicitação foi feita, o serviço pode cobrar um valor extra, informado no momento da conclusão do pedido. A medida garante confiabilidade à transparência do sistema.</p><br>
                        <p>A taxa garante que você possa pedir a comida que quiser, quando quiser, mesmo que o Uber Eats esteja com alta demanda em determinadas área. O preço dinâmico é calculado ao levar em conta o número de pedidos feitos no momento em determinada região e a quantidade de entregadores disponíveis. O solicitante pagará o valor do pedido, o custo fixo (e a taxa extra, quando houver) e os impostos aplicáveis em cartão de crédito ou dinheiro.</p>
                    </div>
                    
                    <div class="mesclar">
                        <h4>Restaurantes</h4>
                        <h5>Seus restaurantes favoritos com descontos promocionais</h5>
                    </div>
                    <img src="{%static 'uber/img/mc_donalds.jpg'%}">
                    <div class="uber_comfort">
                        <p>Faça pedidos em seus restaurantes favoritos aqui no Uber Eats, contamos com diversos restaurantes cadastrados, os mais populares como McDonalds, Burguer King, KFC estão conosco, e conosco você consegue descontos promocionais em todos os pedidos pelo site ou pelo aplicativo, confira já as promoções, também é possível verificar as avaliações de cada restaurante, assim como taxa de entrega e espera.</p>
                    </div>
                    
                    <div>
                        <h4>Como conseguir código de desconto?</h4>
                        <p>Os clientes podem obter descontos ao compartilhar via e-mail e redes sociais seu código promocional do serviço, localizado na seção "Pedidos com descontos" no perfil do app. Quando um amigo fizer um pedido pela primeira vez no Uber Eats e utilizar esse código, o usuário também recebe uma sequência para ganhar um abatimento de valor no próximo pedido feito. O benefício expira após três meses.</p>
                    </div>
                    
                    <div>
                        <h4>Como funciona a política de cancelamento?</h4>
                        <p>É possível cancelar um pedido antes do restaurante aceitá-lo. Caso a necessidade de interrupção ocorra após essa etapa, a companhia informa a necessidade de entrar em contato com a equipe de suporte do Uber Eats, para que confirme com o estabelecimento se a comida já começou a ser preparada. "Caso o restaurante já tenha começado a preparar o seu pedido, não será possível fazer o reembolso", explica a empresa.</p>
                    </div>
                    
                    <div class="mesclar">
                        <h4>Tempo de entrega</h4>
                        <h5>Pelo Uber Eats a entrega é mais rápida</h5>
                    </div>
                    <img src="{%static 'uber/img/uber_eats_preparo.png'%}">
                    <div class="uber_bag">
                        <p>O tempo de entrega é calculado a partir de uma estimativa que leva em conta o tempo médio de preparo da comida mais o necessário para o entregador levar o pedido ao destino final. O tempo real de entrega pode variar, dependendo do movimento no restaurante, do tamanho do seu pedido, das condições do trânsito e de outros fatores.</p>
                    </div>
                    
                    <div class="mesclar botoes_uber_eats">
                        
                        <a class="botao_uber_eats" href="https://play.google.com/store/apps/details?id=com.ubercab.eats&hl=pt_BR">Google Play: Uber <span>Eats</span> <i class="fas fa-download"></i></a>
                    
                        <a class="botao_uber_eats" href="https://apps.apple.com/us/app/uber-eats-food-delivery/id1058959277">App Store: Uber <span>Eats</span> <i class="fas fa-download"></i></a>
                    </div>
                </div>
                <!-- Fim Uber Eats -->
                
                <!-- Serviços -->
                <div class="servicos servicos_inferior">

                    {%include 'uber/parciais/ser_cat.html'%}
                    <a href="{%url 'uber:servicos'%}">Saiba mais<i class="fas fa-angle-right"></i></a>
                </div>
                    {%include 'uber/parciais/ser_mob.html'%}
                    <a href="{%url 'uber:mobile'%}">Saiba mais<i class="fas fa-angle-right"></i></a>
                  </div>
                
                </div>
                <!-- Fim Serviços -->
                
            </main>
            <!-- Fim Conteúdo Principal -->
            
            {%include 'uber/parciais/footer.html'%}

        </div>
    
    </body>
</html>

uber/templates/uber/parciais/footer.html
{%load static%}
<!-- Rodapé -->
<footer class="footer">
    <ul class="sobre">
        <li><h3>Sobre</h3></li>
        <li><a href="{%url 'uber:sobre'%}">Quem somos</a></li>
        <li><a href="{%url 'uber:sobre'%}">Como a Uber funciona</a></li>
        <li><a href="{%url 'uber:sobre'%}">Parcerias</a></li>
    </ul>
    
    <ul class="serviços">
        <li><h3>Serviços</h3></li>
        <li><a href="{%url 'uber:servicos'%}">Categorias Uber</a></li>
        <li><a href="{%url 'uber:eats'%}">Uber Eats</a></li>
        <li><a href="{%url 'uber:mobile'%}">Downloads</a></li>
    </ul>
    
    <ul class="contatos">
        <li><h3>Contato</h3></li>
        <li><a href="{%url 'uber:contato'%}">Suporte</a></li>
        <li><a href="{%url 'uber:contato'%}">Comentários</a></li>
        <li><a href="{%url 'uber:contato'%}">Avalie-nos</a></li>
    </ul>
    
    <!-- Botoes Redes Sociais -->
    <nav class="botoes_inferiores">
        <ul>
            <li><a href="https://www.facebook.com/uberbr/?brand_redir=120945717945722"><i class="fab fa-facebook"></i></a></li>
            <li><a href="https://twitter.com/uber?uclick_id=5797cbf2-698f-42ac-8bcf-1f02a7bf745b"><i class="fab fa-twitter"></i></a></li>
            <li><a href="https://www.youtube.com/channel/UCgnxoUwDmmyzeigmmcf0hZA?uclick_id=5797cbf2-698f-42ac-8bcf-1f02a7bf745b"><i class="fab fa-youtube"></i></a></li>
            <li><a href="https://www.linkedin.com/company/uber-com/"><i class="fab fa-linkedin-in"></i></a></li>
            <li><a href="https://www.instagram.com/uber/?uclick_id=5797cbf2-698f-42ac-8bcf-1f02a7bf745b"><i class="fab fa-instagram"></i></a></li>
        </ul>
    </nav>
    
    <!-- Ícones de Download -->
    <ul class="icones_download">
        <li><a href="https://apps.apple.com/us/app/uber/id368677368?uclick_id=1e3e3bed-1d47-4c1d-a82f-41a149feb678"><img src="{%static 'uber/img/app_store_icone.png'%}"></a></li>
        <li><a href="https://play.google.com/store/apps/details?id=com.ubercab&uclick_id=1e3e3bed-1d47-4c1d-a82f-41a149feb678"><img src="{%static 'uber/img/google_play_icone.png'%}"></a></li>
    </ul>
    
    <script src="{%static 'uber/js/script.js'%}"></script>

    <div class="footer_absoluto">
        <a href="{%url 'uber:home'%}" class="logo"><h1>Uber</h1></a>
    </div>



</footer>
<!-- Fim Rodapé -->

uber/templates/uber/parciais/header.html
<header class="header">
    <a href="{%url 'uber:home'%}" class="logo"><h1>Uber</h1></a>

    <nav class="nav">
        <ul>
            <li><a href="{%url 'uber:sobre'%}">Sobre</a></li>
            <li><a href="{%url 'uber:servicos'%}">Serviços</a></li>
            <li><a href="{%url 'uber:contato'%}">Contato</a></li>
            <i class="far fa-user"></i>
            <li><a href="{%url 'uber:login'%}">Entrar</a></li>
            <li><a href="{%url 'uber:register'%}">Cadastrar</a></li>
        </ul>
    </nav>
    
</header>

uber/templates/uber/parciais/menu_lateral.html
<nav class="sidenav">
    <ul>
        
        <li class="side_logo">
            <a href="{%url 'uber:home'%}"><i class="fab fa-uber"></i><span>Uber</span></a>
        </li>
        
        <!-- Ícones -->
        <li>
            <a href="{%url 'uber:servicos'%}"><i class="fas fa-th-large"></i><span>Categorias</span></a>
        </li>
        <li>
            <a href="{%url 'uber:eats'%}"><i class="fas fa-utensils"></i><span>Uber Eats</span></a>
        </li>
        <li>
            <a href="{%url 'uber:contato'%}"><i class="far fa-comments"></i><span>Comentários</span></a>
        </li>
        <li>
            <a href="{%url 'uber:contato'%}"><i class="far fa-question-circle"></i><span>Suporte</span></a>
        </li>
        <li>
            <a href="{%url 'uber:contato'%}"><i class="fas fa-star-half-alt"></i><span>Avalie-nos</span></a>
        </li>
    </ul>
</nav>
<!-- Fim Navegação Lateral -->

uber/templates/uber/parciais/ser_cat.html
{%load static%}

<div class="categorias">
    <img src="{%static 'uber/img/uber_comfort_cartao.jpg'%}" alt="Categorias">
    <h4>Categorias</h4>
    <p>Um uber para cada necessidade, descubra qual o tipo de Uber que melhor se encaixa a suas necessidades e ao seu bolso.</p>